
import { SelectOption } from './types';

export const MAX_CHARACTERS = 6;

export const CAMERA_MOVEMENT_OPTIONS: SelectOption[] = [
  { value: "", label: "Pilih Gerakan Kamera..." },
  { value: "none", label: "None (Tidak Ada)" },
  { value: "static_shot", label: "Static Shot (Pengambilan Gambar Statis)" },
  { value: "pan_left", label: "Pan Left (Geser Kiri)" },
  { value: "pan_right", label: "Pan Right (Geser Kanan)" },
  { value: "tilt_up", label: "Tilt Up (Dongak ke Atas)" },
  { value: "tilt_down", label: "Tilt Down (Tunduk ke Bawah)" },
  { value: "zoom_in", label: "Zoom In (Perbesar)" },
  { value: "zoom_out", label: "Zoom Out (Perkecil)" },
  { value: "dolly_in", label: "Dolly In (Dolly Masuk)" },
  { value: "dolly_out", label: "Dolly Out (Dolly Keluar)" },
  { value: "truck_left", label: "Truck Left (Geser Kamera Kiri)" },
  { value: "truck_right", label: "Truck Right (Geser Kamera Kanan)" },
  { value: "pedestal_up", label: "Pedestal Up (Pedestal Naik)" },
  { value: "pedestal_down", label: "Pedestal Down (Pedestal Turun)" },
  { value: "crane_shot_up", label: "Crane Shot Up (Pengambilan Gambar Derek Naik)" },
  { value: "crane_shot_down", label: "Crane Shot Down (Pengambilan Gambar Derek Turun)" },
  { value: "tracking_shot", label: "Tracking Shot / Follow Shot (Pengambilan Gambar Mengikuti)" },
  { value: "steadicam_shot", label: "Steadicam Shot (Pengambilan Gambar Steadicam)" },
  { value: "handheld_shot", label: "Handheld Shot (Pengambilan Gambar Genggam)" },
  { value: "aerial_shot", label: "Aerial Shot / Drone Shot (Pengambilan Gambar Udara / Drone)" },
  { value: "orbit_shot", label: "Orbit / 360 Degree Shot (Mengorbit / Pengambilan Gambar 360 Derajat)" },
  { value: "arc_shot", label: "Arc Shot (Pengambilan Gambar Melengkung)" },
  { value: "whip_pan", label: "Whip Pan / Swish Pan (Geser Cepat)" },
  { value: "crash_zoom", label: "Crash Zoom / Snap Zoom (Zoom Cepat)" },
  { value: "dutch_angle", label: "Dutch Angle / Dutch Tilt (Sudut Belanda)" },
  { value: "vertigo_effect", label: "Vertigo Effect / Dolly Zoom (Efek Vertigo / Dolly Zoom)" },
  { value: "slow_motion", label: "Slow Motion (Gerak Lambat)" },
  { value: "fast_motion", label: "Fast Motion / Time-Lapse (Gerak Cepat / Selang Waktu)" },
  { value: "reverse_motion", label: "Reverse Motion (Gerak Mundur)" },
  { value: "jib_shot", label: "Jib Shot (Pengambilan Gambar Jib)" },
  { value: "snorricam_shot", label: "Snorricam Shot (Pengambilan Gambar Snorricam)" },
  { value: "bullet_time", label: "Bullet Time (Waktu Peluru)" },
  { value: "3d_rotation_x", label: "3D Rotation (X-axis) (Rotasi 3D - Sumbu X)" },
  { value: "3d_rotation_y", label: "3D Rotation (Y-axis) (Rotasi 3D - Sumbu Y)" },
  { value: "3d_rotation_z", label: "3D Rotation (Z-axis) (Rotasi 3D - Sumbu Z)" },
  { value: "roll", label: "Roll (Bergulir)" },
];

export const LIGHTING_OPTIONS: SelectOption[] = [
  { value: "", label: "Pilih Pencahayaan..." },
  { value: "natural_day", label: "Natural Light (Day) (Cahaya Alami - Siang)" },
  { value: "natural_night", label: "Natural Light (Night) (Cahaya Alami - Malam)" },
  { value: "golden_hour", label: "Golden Hour (Jam Emas)" },
  { value: "blue_hour", label: "Blue Hour (Jam Biru)" },
  { value: "studio_lighting", label: "Studio Lighting (Pencahayaan Studio)" },
  { value: "high_key", label: "High Key (Kunci Tinggi)" },
  { value: "low_key", label: "Low Key (Kunci Rendah)" },
  { value: "backlight", label: "Backlight (Cahaya Latar)" },
  { value: "silhouette", label: "Silhouette (Siluet)" },
  { value: "spotlight", label: "Spotlight (Lampu Sorot)" },
  { value: "neon_lights", label: "Neon Lights (Lampu Neon)" },
  { value: "candlelight", label: "Candlelight (Cahaya Lilin)" },
  { value: "moonlight", label: "Moonlight (Cahaya Bulan)" },
  { value: "cinematic_lighting", label: "Cinematic Lighting (Pencahayaan Sinematik)" },
  { value: "dramatic_lighting", label: "Dramatic Lighting (Pencahayaan Dramatis)" },
];

export const VIDEO_STYLE_OPTIONS: SelectOption[] = [
  { value: "", label: "Pilih Gaya Video..." },
  { value: "photorealistic", label: "Photorealistic (Fotorealistis)" },
  { value: "cinematic", label: "Cinematic (Sinematik)" },
  { value: "animated_2d", label: "Animated (2D) (Animasi 2D)" },
  { value: "animated_3d", label: "Animated (3D) (Animasi 3D)" },
  { value: "anime", label: "Anime (Anime)" },
  { value: "claymation", label: "Claymation (Animasi Tanah Liat)" },
  { value: "stop_motion", label: "Stop Motion (Stop Motion)" },
  { value: "documentary", label: "Documentary (Dokumenter)" },
  { value: "vintage_retro", label: "Vintage / Retro (Antik / Retro)" },
  { value: "film_noir", label: "Film Noir (Film Noir)" },
  { value: "sci_fi", label: "Sci-Fi (Fiksi Ilmiah)" },
  { value: "fantasy", label: "Fantasy (Fantasi)" },
  { value: "horror", label: "Horror (Horor)" },
  { value: "surreal", label: "Surreal (Surealis)" },
  { value: "impressionistic", label: "Impressionistic (Impresionistis)" },
  { value: "watercolor", label: "Watercolor (Cat Air)" },
  { value: "sketch", label: "Sketch (Sketsa)" },
  { value: "pixel_art", label: "Pixel Art (Seni Piksel)" },
];
